version: "3.9"

services:

  postgres:
    image: postgres:15
    container_name: anunciacerto-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: anunciacerto
    ports:
      # Alterado para 5433 para não sobrescrever o banco antigo (5432) e preservar dados valiosos
      - "5433:5432"
    volumes:
      - postgres_nfc_data:/var/lib/postgresql/data

volumes:
  # Alterado de postgres_data para postgres_nfc_data para garantir 100% que os dados antigos fiquem intactos
  postgres_nfc_data: